"""empty message

Revision ID: 2d2289cf67f
Revises: 4159dc7ac378
Create Date: 2014-09-17 14:57:40.388838

"""

# revision identifiers, used by Alembic.
revision = '2d2289cf67f'
down_revision = '4159dc7ac378'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
