"""empty message

Revision ID: 2f4048c60d52
Revises: 2d2289cf67f
Create Date: 2014-09-22 19:33:52.707194

"""

# revision identifiers, used by Alembic.
revision = '2f4048c60d52'
down_revision = '2d2289cf67f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
