"""empty message

Revision ID: 493ea2559506
Revises: 1c2368e0deee
Create Date: 2014-09-16 12:09:54.502118

"""

# revision identifiers, used by Alembic.
revision = '493ea2559506'
down_revision = '1c2368e0deee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
