"""empty message

Revision ID: 28c53fb80f24
Revises: 402bcb0eacb8
Create Date: 2014-09-01 20:10:49.319000

"""

# revision identifiers, used by Alembic.
revision = '28c53fb80f24'
down_revision = '402bcb0eacb8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
