"""empty message

Revision ID: 3790536d2bda
Revises: 28c53fb80f24
Create Date: 2014-09-03 17:43:50.261000

"""

# revision identifiers, used by Alembic.
revision = '3790536d2bda'
down_revision = '28c53fb80f24'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
