"""empty message

Revision ID: 402bcb0eacb8
Revises: 42e9f9930cf2
Create Date: 2014-08-30 18:47:37.882000

"""

# revision identifiers, used by Alembic.
revision = '402bcb0eacb8'
down_revision = '42e9f9930cf2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
