"""empty message

Revision ID: 42e9f9930cf2
Revises: 4df224d139e9
Create Date: 2014-08-30 18:06:40.775000

"""

# revision identifiers, used by Alembic.
revision = '42e9f9930cf2'
down_revision = '4df224d139e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
