"""empty message

Revision ID: 4df224d139e9
Revises: 25f243157c35
Create Date: 2014-08-30 17:22:21.458000

"""

# revision identifiers, used by Alembic.
revision = '4df224d139e9'
down_revision = '25f243157c35'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('contact_open', sa.String(length=255), nullable=True))
    op.add_column('event', sa.Column('date_end', sa.String(length=255), nullable=True))
    op.add_column('event', sa.Column('date_start', sa.String(length=255), nullable=True))
    op.drop_column('event', 'date_start_day')
    op.drop_column('event', 'date_start_hour')
    op.drop_column('event', 'date_start_year')
    op.drop_column('event', 'date_end_hour')
    op.drop_column('event', 'date_start_minute')
    op.drop_column('event', 'date_end_minute')
    op.drop_column('event', 'date_end_day')
    op.drop_column('event', 'date_start_month')
    op.drop_column('event', 'date_end_year')
    op.drop_column('event', 'date_end_month')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date_end_month', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('date_end_year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('date_start_month', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('date_end_day', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('date_end_minute', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('date_start_minute', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('date_end_hour', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('date_start_year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('date_start_hour', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('date_start_day', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('event', 'date_start')
    op.drop_column('event', 'date_end')
    op.drop_column('event', 'contact_open')
    ### end Alembic commands ###
