"""empty message

Revision ID: 61e4c2ce044
Revises: 6d7dc7c3696
Create Date: 2014-08-18 21:55:21.228000

"""

# revision identifiers, used by Alembic.
revision = '61e4c2ce044'
down_revision = '6d7dc7c3696'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
